### ISSUE TITLE
Question about dev status and pypi release

### ISSUE THREAD

**Issue by COLABORATI** [mk-fg/feedjack#7]
Hi, playing around with this repo I found the other branch on allo-/feedjack, but no pull requests or merges? What is the status of these two repos? Will you merge the changes or is the allo- branch just a new 'inofficial' fork that will just exist in parallel to this repo? 

Also I would like to now: which version of the code is currently hosted on pypi? On pypi I see 'Feedjack 15.5.1' - but there is no 15.5.1 branch or tag to be found in this repo and I do not understand the relation between the branches / tags / releases here and the pypi release. Which branch made it to pypi?

Thanks for your attention!

**Comment by mk-fg** [comment]
> I found the other branch on allo-/feedjack, but no pull requests or merges

I think @allo- clarified that in [allo-/feedjack#14](https://github.com/allo-/feedjack/issues/14).

> What is the status of these two repos

See [my comment on allo-/feedjack#14](https://github.com/allo-/feedjack/issues/14#issuecomment-236934236) and @allo-'s comments there.

> Will you merge the changes

Not unless I'll start working on the thing again - a possibility that is safe to ignore, I think, unfortunately.

> is the allo- branch just a new 'inofficial' fork that will just exist in parallel to this repo?

I see why mk-fg/feedjack can be seen as "official" (which it totally shouldn't be at this point), due to some github ui and pypi perks (see [comment on allo-/feedjack#14](https://github.com/allo-/feedjack/issues/14#issuecomment-236934236) for details), but it's actually nothing more than my personal repo.

I think @allo-'s repo should probably be considered "best source" for this project at this point.

> On pypi I see 'Feedjack 15.5.1' - but there is no 15.5.1 branch or tag to be found in this repo

Version comes from setup.py, and it's from mk-fg/feedjack.

For all my projects that are on pypi (and hence need version in setup.py) I simply have git pre-commit hook to put auto-generated "yy.m.n" version (where n - sequential number of commit since start of the month) into setup.py, and don't bother with tags (as it'd be one tag per commit).

> Which branch made it to pypi?

mk-fg/feedjack, i.e. this repo.

> Thanks for your attention!

Thanks to you guys for caring about the thing at all! ;)
